CREATE TABLE [Articulo].[Art_SolDetalle] (
    [IdSolicitud]         BIGINT          NOT NULL,
    [IdDetalle]           BIGINT          NOT NULL,
    [CodReferencia]       VARCHAR (30)    NULL,
    [Marca]               VARCHAR (10)    NULL,
    [MarcaNueva]          VARCHAR (50)    NULL,
    [Descripcion]         VARCHAR (100)   NULL,
    [TextoBreve]          VARCHAR (200)   NULL,
    [PaisOrigen]          VARCHAR (10)    NULL,
    [RegionOrigen]        VARCHAR (10)    NULL,
    [TamArticulo]         VARCHAR (50)    NULL,
    [GradoAlcohol]        VARCHAR (10)    NULL,
    [Color]               VARCHAR (10)    NULL,
    [Talla]               VARCHAR (10)    NULL,
    [Fragancia]           VARCHAR (10)    NULL,
    [Tipos]               VARCHAR (10)    NULL,
    [Sabor]               VARCHAR (10)    NULL,
    [Modelo]              VARCHAR (50)    NULL,
    [RegistroSanitario]   VARCHAR (10)    NULL,
    [ClacificacionFiscal] VARCHAR (10)    NULL,
    [Deducible]           VARCHAR (10)    NULL,
    [Retencion]           VARCHAR (10)    NULL,
    [CodSapArticulo]      VARCHAR (18)    NULL,
    [CodLegacy]           VARCHAR (10)    NULL,
    [OrganizacionCompras] VARCHAR (10)    NULL,
    [FrecuenciaEntrega]   VARCHAR (10)    NULL,
    [TipoMaterial]        VARCHAR (10)    NULL,
    [CategoriaMaterial]   VARCHAR (10)    NULL,
    [GrupoArticulo]       VARCHAR (10)    NULL,
    [SeccionArticulo]     VARCHAR (10)    NULL,
    [SurtidoParcial]      VARCHAR (10)    NULL,
    [Materia]             VARCHAR (10)    NULL,
    [CostoFOB]            NUMERIC (11, 4) NULL,
    [IndPedido]           VARCHAR (10)    NULL,
    [PerfilDistribucion]  VARCHAR (10)    NULL,
    [GrupoCompra]         VARCHAR (10)    NULL,
    [CategoriaValoracion] VARCHAR (10)    NULL,
    [TipoAlamcen]         VARCHAR (10)    NULL,
    [CondicionAlmacen]    VARCHAR (10)    NULL,
    [ClListaSurtido]      VARCHAR (10)    NULL,
    [EstatusMaterial]     VARCHAR (10)    NULL,
    [EstatusVenta]        VARCHAR (10)    NULL,
    [ValidoDesde]         DATETIME        NULL,
    [GrupoBalanzas]       VARCHAR (10)    NULL,
    [Observacion]         VARCHAR (500)   NULL,
    [Coleccion]           VARCHAR (10)    NULL,
    [Temporada]           VARCHAR (10)    NULL,
    [Estacion]            VARCHAR (10)    NULL,
    [JerarquiaProd]       VARCHAR (10)    NULL,
    [SusceptBonifEsp]     VARCHAR (10)    NULL,
    [ProcedimCatalog]     VARCHAR (10)    NULL,
    [CaracterPlanNec]     VARCHAR (10)    NULL,
    [FuenteProvision]     VARCHAR (10)    NULL,
    [EstadoSolicitud]     VARCHAR (10)    NULL,
    [EstadoArticulo]      VARCHAR (10)    NULL,
    [EsGenerico]          BIT             NULL,
    [PrecioBruto]         NUMERIC (11, 3) NULL,
    [Descuento1]          NUMERIC (11, 3) NULL,
    [Descuento2]          NUMERIC (11, 3) NULL,
    [ImpuestoVerde]       BIT             NULL,
    [Cantidad]            INT             NULL,
    [PrecioNuevo]         NUMERIC (11, 3) NULL,
    [Variante]            BIT             NULL,
    [Generico]            BIT             NULL,
    [CodGenerico]         BIGINT          NULL,
    CONSTRAINT [PK_ART_SOLDETALLE] PRIMARY KEY CLUSTERED ([IdDetalle] ASC, [IdSolicitud] ASC),
    CONSTRAINT [FK_Detalle_Solicitud] FOREIGN KEY ([IdSolicitud]) REFERENCES [Articulo].[Art_Solicitud] ([IdSolicitud])
);

