//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clibCustom.WCFEnvioCorreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFEnvioCorreo.ServEnvioClientSoap")]
    public interface ServEnvioClientSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PI_UsrEnvia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaCorreoDF", ReplyAction="*")]
        clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse EnviaCorreoDF(clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaCorreoDF", ReplyAction="*")]
        System.Threading.Tasks.Task<clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse> EnviaCorreoDFAsync(clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCorreoDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCorreoDF", Namespace="http://tempuri.org/", Order=0)]
        public clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequestBody Body;
        
        public EnviaCorreoDFRequest() {
        }
        
        public EnviaCorreoDFRequest(clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaCorreoDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PI_UsrEnvia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PI_UsrDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PI_UsrDestinoCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PI_UsrDestinoCCO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PI_Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PI_Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool PI_MostrarLogo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool PI_EsHTML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool PI_TieneAdjuntos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] PI_Adjunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PI_NombrePlantilla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PI_Variables;
        
        public EnviaCorreoDFRequestBody() {
        }
        
        public EnviaCorreoDFRequestBody(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            this.PI_UsrEnvia = PI_UsrEnvia;
            this.PI_UsrDestino = PI_UsrDestino;
            this.PI_UsrDestinoCC = PI_UsrDestinoCC;
            this.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            this.PI_Asunto = PI_Asunto;
            this.PI_Mensaje = PI_Mensaje;
            this.PI_MostrarLogo = PI_MostrarLogo;
            this.PI_EsHTML = PI_EsHTML;
            this.PI_TieneAdjuntos = PI_TieneAdjuntos;
            this.PI_Adjunto = PI_Adjunto;
            this.fileName = fileName;
            this.PI_NombrePlantilla = PI_NombrePlantilla;
            this.PI_Variables = PI_Variables;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCorreoDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCorreoDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponseBody Body;
        
        public EnviaCorreoDFResponse() {
        }
        
        public EnviaCorreoDFResponse(clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaCorreoDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaCorreoDFResult;
        
        public EnviaCorreoDFResponseBody() {
        }
        
        public EnviaCorreoDFResponseBody(string EnviaCorreoDFResult) {
            this.EnviaCorreoDFResult = EnviaCorreoDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServEnvioClientSoapChannel : clibCustom.WCFEnvioCorreo.ServEnvioClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServEnvioClientSoapClient : System.ServiceModel.ClientBase<clibCustom.WCFEnvioCorreo.ServEnvioClientSoap>, clibCustom.WCFEnvioCorreo.ServEnvioClientSoap {
        
        public ServEnvioClientSoapClient() {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServEnvioClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse clibCustom.WCFEnvioCorreo.ServEnvioClientSoap.EnviaCorreoDF(clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest request) {
            return base.Channel.EnviaCorreoDF(request);
        }
        
        public string EnviaCorreoDF(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest inValue = new clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest();
            inValue.Body = new clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            inValue.Body.PI_NombrePlantilla = PI_NombrePlantilla;
            inValue.Body.PI_Variables = PI_Variables;
            clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse retVal = ((clibCustom.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviaCorreoDF(inValue);
            return retVal.Body.EnviaCorreoDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse> clibCustom.WCFEnvioCorreo.ServEnvioClientSoap.EnviaCorreoDFAsync(clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest request) {
            return base.Channel.EnviaCorreoDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<clibCustom.WCFEnvioCorreo.EnviaCorreoDFResponse> EnviaCorreoDFAsync(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest inValue = new clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequest();
            inValue.Body = new clibCustom.WCFEnvioCorreo.EnviaCorreoDFRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            inValue.Body.PI_NombrePlantilla = PI_NombrePlantilla;
            inValue.Body.PI_Variables = PI_Variables;
            return ((clibCustom.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviaCorreoDFAsync(inValue);
        }
    }
}
