//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProcesoBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59688/ServEnvioClient.asmx")]
        public string WSProcesoBase_correo_ServEnvioClient {
            get {
                return ((string)(this["WSProcesoBase_correo_ServEnvioClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://piprd.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_PORTAL_PROVEEDORES_PIP&receiverParty=&receiverService=&interface=SI_CrossDockDistr_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Asipecom%3Apedidos%3ACrossDockDistr")]
        public string WSProcesoBase_Sap_EnvioPedidoCross_SI_CrossDockDistr_OUT_SYNCService {
            get {
                return ((string)(this["WSProcesoBase_Sap_EnvioPedidoCross_SI_CrossDockDistr_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piprd.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderS" +
            "ervice=BS_PORTAL_PROVEEDORES_PIP&receiverParty=&receiverService=&interface=SI_So" +
            "licitudCita_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Asipecom%3Apedidos%3" +
            "ASolicitudCita")]
        public string WSProcesoBase_WS_SolicitudCitasCER_SI_SolicitudCita_OUT_SYNCService {
            get {
                return ((string)(this["WSProcesoBase_WS_SolicitudCitasCER_SI_SolicitudCita_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://proveedorarp.elrosado.com/WS_CITA_PROVEEDORES/WS_CITAS_SIPECOM.asmx")]
        public string WSProcesoBase_WSNuoBuscarHorarios_WS_CITAS_SIPECOM {
            get {
                return ((string)(this["WSProcesoBase_WSNuoBuscarHorarios_WS_CITAS_SIPECOM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://piprd.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_PORTAL_PROVEEDORES_PIP&receiverParty=&receiverService=&interface=SI_ConsultarStock_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Asipecom%3Apedidos%3AConsultarStock")]
        public string WSProcesoBase_wsReporteStock_SI_ConsultarStock_OUT_SYNCService {
            get {
                return ((string)(this["WSProcesoBase_wsReporteStock_SI_ConsultarStock_OUT_SYNCService"]));
            }
        }
    }
}
