CREATE TABLE [Pedidos].[Ped_Pedido] (
    [IdEmpresa]             INT             NOT NULL,
    [NumPedido]             VARCHAR (10)    NOT NULL,
    [CodAlmacen]            VARCHAR (4)     NOT NULL,
    [NomAlmacen]            VARCHAR (30)    NOT NULL,
    [FechaPedido]           DATETIME        NOT NULL,
    [CodAlmDestino]         VARCHAR (4)     NOT NULL,
    [CodProveedor]          VARCHAR (10)    NOT NULL,
    [NomProveedor]          VARCHAR (35)    NOT NULL,
    [ZonaOrigen]            VARCHAR (3)     NOT NULL,
    [Estado]                VARCHAR (2)     NOT NULL,
    [Origen]                VARCHAR (1)     NOT NULL,
    [EsDescargado]          BIT             NOT NULL,
    [EsImpreso]             BIT             NOT NULL,
    [CodProveedorOriginal]  VARCHAR (10)    NULL,
    [CodAlmacenOriginal]    VARCHAR (4)     NULL,
    [CodAlmDestinoOriginal] VARCHAR (4)     NULL,
    [IdPedido]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [SubTotSinImp]          NUMERIC (18, 2) NULL,
    [FechaCarga]            DATETIME        DEFAULT (getdate()) NULL,
    [FechaDescarga]         DATETIME        NULL,
    [FechaImpresion]        DATETIME        NULL,
    [UsuarioDescarga]       VARCHAR (20)    NULL,
    [UsuarioImprime]        VARCHAR (20)    NULL,
    [IsCross]               BIT             NULL,
    [TipoPedido]            VARCHAR (1)     NULL,
    [EstadoDistribucion]    VARCHAR (1)     NULL,
    [IdChofer]              VARCHAR (13)    NULL,
    [NombreChofer]          VARCHAR (40)    NULL,
    [FechaBloqueo]          DATETIME        NULL,
    [CodSociedad]           VARCHAR (4)     NULL,
    [CodCiudadAlmacen]      VARCHAR (4)     NULL,
    [NomCiudadAlmacen]      VARCHAR (30)    NULL,
    [NumContrato]           VARCHAR (11)    NULL,
    [FecIniContrato]        DATETIME        NULL,
    [FecFinContrato]        DATETIME        NULL,
    [LineaNegocio]          VARCHAR (1)     NULL,
    [RUCSociedad]           VARCHAR (13)    NULL,
    [RUC]                   VARCHAR (13)    NULL,
    [estadobloqueo]         INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Ped_Pedido] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdPedido] ASC) ON [Pedidos]
) ON [Pedidos];

