CREATE TABLE [Proveedor].[CMPro_Proveedor_tmp] (
    [CodProveedor]      VARCHAR (25)   NULL,
    [Ruc]               VARCHAR (25)   NULL,
    [TipoProveedor]     VARCHAR (10)   NULL,
    [NombreProveedor]   VARCHAR (260)  NULL,
    [DirCalleNum]       VARCHAR (95)   NULL,
    [DirPisoEdificio]   VARCHAR (4)    NULL,
    [DirPrincipal]      VARCHAR (95)   NULL,
    [DirDistrito]       VARCHAR (4)    NULL,
    [DirCodPostal]      VARCHAR (12)   NULL,
    [Ciudad]            VARCHAR (65)   NULL,
    [Pais]              VARCHAR (10)   NULL,
    [Region]            VARCHAR (3)    NULL,
    [Idioma]            VARCHAR (4)    NULL,
    [Phone]             VARCHAR (50)   NULL,
    [Movil]             VARCHAR (4)    NULL,
    [Fax]               VARCHAR (4)    NULL,
    [email]             VARCHAR (260)  NULL,
    [Gendocelec]        VARCHAR (4)    NULL,
    [FechaCreacion]     VARCHAR (25)   NULL,
    [Apoderadonom]      VARCHAR (4)    NULL,
    [ApoderadoApe]      VARCHAR (4)    NULL,
    [ApoderadoFiscal]   VARCHAR (4)    NULL,
    [FechaModificacion] VARCHAR (25)   NULL,
    [NombreContacto]    VARCHAR (4)    NULL,
    [CorreoContacto]    VARCHAR (4)    NULL,
    [CelularContacto]   VARCHAR (4)    NULL,
    [ProveedorCritico]  VARCHAR (4)    NULL,
    [ProcesoSoporte]    VARCHAR (1100) NULL,
    [Area]              VARCHAR (250)  NULL,
    [ServAuxiliares]    VARCHAR (4)    NULL,
    [FormaPago]         VARCHAR (25)   NULL,
    [Status]            VARCHAR (25)   NULL,
    [NivelRiesgo]       VARCHAR (20)   NULL,
    [Cumplimiento]      VARCHAR (4)    NULL,
    [LlenadoDocVin]     VARCHAR (4)    NULL,
    [VinculadoBG]       VARCHAR (4)    NULL,
    [Recurrente]        VARCHAR (4)    NULL,
    [FirmSegInfo]       VARCHAR (4)    NULL,
    [FirmadoPCI]        VARCHAR (4)    NULL,
    [CalContNeg]        VARCHAR (20)   NULL,
    [EvalDes2018]       VARCHAR (20)   NULL,
    [EvalDes2019]       VARCHAR (20)   NULL,
    [EvalDes2020]       VARCHAR (20)   NULL,
    [Fact2019]          VARCHAR (20)   NULL,
    [Fact2020]          VARCHAR (20)   NULL,
    [Fact2021]          VARCHAR (20)   NULL,
    [SGS]               VARCHAR (75)   NULL,
    [CalObtenida]       VARCHAR (75)   NULL,
    [FechaTermCal]      VARCHAR (35)   NULL
);


GO
CREATE NONCLUSTERED INDEX [Idx_CodProveedor_01]
    ON [Proveedor].[CMPro_Proveedor_tmp]([CodProveedor] ASC);

