CREATE TABLE [Proveedor].[Pro_SolContacto] (
    [IdSolContacto]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [IdSolicitud]               BIGINT        NOT NULL,
    [TipoIdentificacion]        VARCHAR (10)  NULL,
    [Identificacion]            VARCHAR (13)  NULL,
    [Nombre2]                   VARCHAR (35)  NULL,
    [Nombre1]                   VARCHAR (35)  NULL,
    [Apellido2]                 VARCHAR (35)  NULL,
    [Apellido1]                 VARCHAR (35)  NULL,
    [CodSapContacto]            VARCHAR (15)  NULL,
    [PreFijo]                   VARCHAR (30)  NULL,
    [DepCliente]                VARCHAR (12)  NULL,
    [Departamento]              VARCHAR (4)   NULL,
    [Funcion]                   VARCHAR (2)   NULL,
    [RepLegal]                  BIT           NULL,
    [Estado]                    BIT           NULL,
    [NotElectronica]            BIT           NULL,
    [NotTransBancaria]          BIT           NULL,
    [FechaNacimiento]           DATETIME      NULL,
    [Nacionalidad]              VARCHAR (10)  NULL,
    [PaisResidencia]            VARCHAR (20)  NULL,
    [EstadoCivil]               VARCHAR (20)  NULL,
    [ConyugeTipoIdentificacion] VARCHAR (10)  NULL,
    [ConyugeIdentificacion]     VARCHAR (20)  NULL,
    [ConyugeNombres]            VARCHAR (100) NULL,
    [RegimenMatrimonial]        VARCHAR (20)  NULL,
    [RelacionDependencia]       VARCHAR (20)  NULL,
    [AntiguedadLaboral]         VARCHAR (10)  NULL,
    [TipoIngreso]               VARCHAR (20)  NULL,
    [IngresoMensual]            VARCHAR (10)  NULL,
    [ConyugeApellidos]          VARCHAR (100) NULL,
    [ConyugeFechaNac]           DATETIME      NULL,
    [ConyugeNacionalidad]       VARCHAR (10)  NULL,
    [TipoParticipante]          VARCHAR (10)  NULL,
    CONSTRAINT [PK_PRO_SOLCONTACTO] PRIMARY KEY CLUSTERED ([IdSolContacto] ASC),
    CONSTRAINT [FK_PRO_SOLC_REFERENCE_PRO_SOLP] FOREIGN KEY ([IdSolicitud]) REFERENCES [Proveedor].[Pro_SolProveedor] ([IdSolicitud])
);

