//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSProcesoBase.wsReporteStock {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ConsultarStock_OUT_SYNCBinding", Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class SI_ConsultarStock_OUT_SYNCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ConsultarStock_OUT_SYNCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ConsultarStock_OUT_SYNCService() {
            this.Url = global::WSProcesoBase.Properties.Settings.Default.WSProcesoBase_wsReporteStock_SI_ConsultarStock_OUT_SYNCService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ConsultarStock_OUT_SYNCCompletedEventHandler SI_ConsultarStock_OUT_SYNCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_ConsultarStock_Response", Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
        public DT_ConsultarStock_Response SI_ConsultarStock_OUT_SYNC([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")] DT_ConsultarStock_Request MT_ConsultarStock_Request) {
            object[] results = this.Invoke("SI_ConsultarStock_OUT_SYNC", new object[] {
                        MT_ConsultarStock_Request});
            return ((DT_ConsultarStock_Response)(results[0]));
        }
        
        /// <remarks/>
        public void SI_ConsultarStock_OUT_SYNCAsync(DT_ConsultarStock_Request MT_ConsultarStock_Request) {
            this.SI_ConsultarStock_OUT_SYNCAsync(MT_ConsultarStock_Request, null);
        }
        
        /// <remarks/>
        public void SI_ConsultarStock_OUT_SYNCAsync(DT_ConsultarStock_Request MT_ConsultarStock_Request, object userState) {
            if ((this.SI_ConsultarStock_OUT_SYNCOperationCompleted == null)) {
                this.SI_ConsultarStock_OUT_SYNCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ConsultarStock_OUT_SYNCOperationCompleted);
            }
            this.InvokeAsync("SI_ConsultarStock_OUT_SYNC", new object[] {
                        MT_ConsultarStock_Request}, this.SI_ConsultarStock_OUT_SYNCOperationCompleted, userState);
        }
        
        private void OnSI_ConsultarStock_OUT_SYNCOperationCompleted(object arg) {
            if ((this.SI_ConsultarStock_OUT_SYNCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ConsultarStock_OUT_SYNCCompleted(this, new SI_ConsultarStock_OUT_SYNCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class DT_ConsultarStock_Request {
        
        private string pS_DATEField;
        
        private string pS_LIFNRField;
        
        private DT_ConsultarStock_RequestITEM[] p_MATNRField;
        
        private DT_ConsultarStock_RequestITEM1[] p_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PS_DATE {
            get {
                return this.pS_DATEField;
            }
            set {
                this.pS_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PS_LIFNR {
            get {
                return this.pS_LIFNRField;
            }
            set {
                this.pS_LIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ConsultarStock_RequestITEM[] P_MATNR {
            get {
                return this.p_MATNRField;
            }
            set {
                this.p_MATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ConsultarStock_RequestITEM1[] P_WERKS {
            get {
                return this.p_WERKSField;
            }
            set {
                this.p_WERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class DT_ConsultarStock_RequestITEM {
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class DT_ConsultarStock_Response {
        
        private DT_ConsultarStock_ResponseITEM[] pT_STOCKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ConsultarStock_ResponseITEM[] PT_STOCK {
            get {
                return this.pT_STOCKField;
            }
            set {
                this.pT_STOCKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class DT_ConsultarStock_ResponseITEM {
        
        private string dATEField;
        
        private string wERKSField;
        
        private string lIFNRField;
        
        private string mATNRField;
        
        private string zIDNLFField;
        
        private string sTOCKField;
        
        private string bASE_UOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDNLF {
            get {
                return this.zIDNLFField;
            }
            set {
                this.zIDNLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCK {
            get {
                return this.sTOCKField;
            }
            set {
                this.sTOCKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:sipecom:pedidos:ConsultarStock")]
    public partial class DT_ConsultarStock_RequestITEM1 {
        
        private string wERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_ConsultarStock_OUT_SYNCCompletedEventHandler(object sender, SI_ConsultarStock_OUT_SYNCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_ConsultarStock_OUT_SYNCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_ConsultarStock_OUT_SYNCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_ConsultarStock_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_ConsultarStock_Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591