declare @v_max int
select @v_max = MAX(Tabla)+1 from Proveedor.Pro_Tabla where Estado = 'A'

if not exists(select 1 from Proveedor.Pro_Tabla where TablaNombre = 'tbl_nacionalidad_neo') 
begin
	insert into Proveedor.Pro_Tabla values(@v_max,'tbl_nacionalidad_neo','A')
	
	insert into Proveedor.Pro_Catalogo 
	values(@v_max,'2176','ANDORRA','A',''),
		(@v_max,'2177','UAE DIRHAM','A',''),
		(@v_max,'2178','EMIRATOS ARABES UNIDOS','A',''),
		(@v_max,'2179','AFGANISTAN','A',''),
		(@v_max,'2180','ANTIGUA','A',''),
		(@v_max,'2181','AFARES Y LOS ISSAS','A',''),
		(@v_max,'2182','ALBANIA','A',''),
		(@v_max,'2183','ARMENIA','A',''),
		(@v_max,'2184','ANTILLAS HOLANDESAS','A',''),
		(@v_max,'2185','ANTILLAS NEERLANDESAS','A',''),
		(@v_max,'2186','ANGOLA','A',''),
		(@v_max,'2187','ANGOLA','A',''),
		(@v_max,'2188','ARGENTINA','A',''),
		(@v_max,'2189','SAMOA AMERICANA','A',''),
		(@v_max,'2190','AUSTRIA','A',''),
		(@v_max,'2191','AUSTRALIA-ISLA DE PASCUA-TUVAL','A',''),
		(@v_max,'2192','ARUBA','A',''),
		(@v_max,'2193','BOSNIA-HERCEGOVINA','A',''),
		(@v_max,'2194','BARBADOS','A',''),
		(@v_max,'2195','BANGLADESH','A',''),
		(@v_max,'2196','BELGICA CONVERTIBLE','A',''),
		(@v_max,'2197','BELGICA CAMBIO','A',''),
		(@v_max,'2198','BELGICA FINANCIERO','A',''),
		(@v_max,'2199','BURQUINA FASO','A',''),
		(@v_max,'2200','BULGARIA','A',''),
		(@v_max,'2201','BAHREIN','A',''),
		(@v_max,'2202','BURUNDI','A',''),
		(@v_max,'2203','RSS DE BIOLORRUSIA','A',''),
		(@v_max,'2204','BERMUDAS','A',''),
		(@v_max,'2205','BRUNEI DARUSSALAM','A',''),
		(@v_max,'2206','BRUNEI','A',''),
		(@v_max,'2207','BOLIVIA','A',''),
		(@v_max,'2208','BRASIL','A',''),
		(@v_max,'2209','BAHAMAS','A',''),
		(@v_max,'2210','BUTAN','A',''),
		(@v_max,'2211','BURMA','A',''),
		(@v_max,'2212','BOTSWANA','A',''),
		(@v_max,'2213','BELICE','A',''),
		(@v_max,'2214','CANADA','A',''),
		(@v_max,'2215','ISLAS COCOS','A',''),
		(@v_max,'2216','REPUBLICA CENTROAFRICANA','A',''),
		(@v_max,'2217','SUIZA','A',''),
		(@v_max,'2218','COSTA DE MARFIL','A',''),
		(@v_max,'2219','ISLAS COOK','A',''),
		(@v_max,'2220','UNIDADES DE FOMENTO CHILE','A',''),
		(@v_max,'2221','CHILE','A',''),
		(@v_max,'2222','CAMERUN','A',''),
		(@v_max,'2223','CHINA','A',''),
		(@v_max,'2224','COLOMBIA','A',''),
		(@v_max,'2225','COSTA RICA','A',''),
		(@v_max,'2226','CHECOSLOVAQUIA','A',''),
		(@v_max,'2227','CUBA','A',''),
		(@v_max,'2228','CABO VERDE','A',''),
		(@v_max,'2229','ISLA DE PASCUA','A',''),
		(@v_max,'2230','ISLAS CANTON Y ENDERBURY','A',''),
		(@v_max,'2231','CYPRUS','A',''),
		(@v_max,'2232','CHIPRE','A',''),
		(@v_max,'2233','BANGADESH','A',''),
		(@v_max,'2234','ALEMANIA DEMOC.','A',''),
		(@v_max,'2235','ALEMANIA FEDERAL','A',''),
		(@v_max,'2236','DJIBOUTI','A',''),
		(@v_max,'2237','DINAMARCA','A',''),
		(@v_max,'2238','REP.DOMINICANA','A',''),
		(@v_max,'2239','DAHOMEY','A',''),
		(@v_max,'2240','ARGELIA','A',''),
		(@v_max,'2241','ECUADOR','A',''),
		(@v_max,'2242','EGIPTO','A',''),
		(@v_max,'2243','SAHARA OCCIDENTAL','A',''),
		(@v_max,'2244','ESLOVAQUIA','A',''),
		(@v_max,'2245','ESPANA CONT.CONV.','A',''),
		(@v_max,'2246','ESLOVENIA','A',''),
		(@v_max,'2247','ESPANA ANDORRA','A',''),
		(@v_max,'2248','ETIOPIA','A',''),
		(@v_max,'2249','CEE','A',''),
		(@v_max,'2250','ESLOVENIA','A',''),
		(@v_max,'2251','FINLANDIA','A',''),
		(@v_max,'2252','FIJI','A',''),
		(@v_max,'2253','ISLAS MALVINAS','A',''),
		(@v_max,'2254','ISLAS FEROE','A',''),
		(@v_max,'2255','FRANCIA-MONACO-MARTINIQUE-GUAD','A',''),
		(@v_max,'2256','GABON','A',''),
		(@v_max,'2257','REINO UNIDO','A',''),
		(@v_max,'2258','GRANADA','A',''),
		(@v_max,'2259','ISLAS GILBERT ELLICE','A',''),
		(@v_max,'2260','GUAYANA FRANCESA','A',''),
		(@v_max,'2261','GHANA','A',''),
		(@v_max,'2262','GHANA','A',''),
		(@v_max,'2263','GIBRALTAR','A',''),
		(@v_max,'2264','GROENLANDIA','A',''),
		(@v_max,'2265','GAMBIA','A',''),
		(@v_max,'2266','GUINEA','A',''),
		(@v_max,'2267','GUADALUPE','A',''),
		(@v_max,'2268','GINEA ECUATORIAL','A',''),
		(@v_max,'2269','GREECE','A',''),
		(@v_max,'2270','GRECIA','A',''),
		(@v_max,'2271','GUATEMALA','A',''),
		(@v_max,'2272','GUAM','A',''),
		(@v_max,'2273','GUINEA BISSAU','A',''),
		(@v_max,'2274','GUYANA','A',''),
		(@v_max,'2275','HONG KONG','A',''),
		(@v_max,'2276','ISLAS HEARD Y MCDONALD','A',''),
		(@v_max,'2277','HONDURAS','A',''),
		(@v_max,'2278','CROACIA','A',''),
		(@v_max,'2279','HAITI','A',''),
		(@v_max,'2280','HUNGRIA','A',''),
		(@v_max,'2281','INDONESIA','A',''),
		(@v_max,'2282','IRLANDA','A',''),
		(@v_max,'2283','ISRAEL','A',''),
		(@v_max,'2284','BHUTAN INDIA','A',''),
		(@v_max,'2285','IRAQ-SAUDI','A',''),
		(@v_max,'2286','IRAQ','A',''),
		(@v_max,'2287','IRAN','A',''),
		(@v_max,'2288','ISLANDIA','A',''),
		(@v_max,'2289','ITALIA SAN MARINO VATICANO','A',''),
		(@v_max,'2290','JAMAICA','A',''),
		(@v_max,'2291','JORDANIA','A',''),
		(@v_max,'2292','JAPON','A',''),
		(@v_max,'2293','ISLA JOHNSTON','A',''),
		(@v_max,'2294','KENYA','A',''),
		(@v_max,'2295','KAMPUCHEA DEM.','A',''),
		(@v_max,'2296','KAMPUCHEA DEMOCRATICA','A',''),
		(@v_max,'2297','COMORAS','A',''),
		(@v_max,'2298','SAN CRISTOBAL Y NEVIS','A',''),
		(@v_max,'2299','COREA REP.DEMOCRATICA POPULAR','A',''),
		(@v_max,'2300','COREA','A',''),
		(@v_max,'2301','KUWAIT','A',''),
		(@v_max,'2302','ISLAS CAIMAN','A',''),
		(@v_max,'2303','ISLAS CAIMAN','A',''),
		(@v_max,'2304','KAZAJSTAN','A',''),
		(@v_max,'2305','REP.DEM. LAO','A',''),
		(@v_max,'2306','LAOS','A',''),
		(@v_max,'2307','LIBANO','A',''),
		(@v_max,'2308','SANTA LUCIA','A',''),
		(@v_max,'2309','LIECHTENSTEIN','A',''),
		(@v_max,'2310','LITUANIA','A',''),
		(@v_max,'2311','SRI LANKA','A',''),
		(@v_max,'2312','LIBERIA','A',''),
		(@v_max,'2313','LESOTHO','A',''),
		(@v_max,'2314','LUXEMBURGO','A',''),
		(@v_max,'2315','LIBIA','A',''),
		(@v_max,'2316','MOROCCO WESTERN SAHARA','A',''),
		(@v_max,'2317','MARRUECOS','A',''),
		(@v_max,'2318','MADAGASCAR','A',''),
		(@v_max,'2319','ISLAS MIDWAY','A',''),
		(@v_max,'2320','MIXTO','A',''),
		(@v_max,'2321','MACEDONIA','A',''),
		(@v_max,'2322','MALI','A',''),
		(@v_max,'2323','MONGOLIA','A',''),
		(@v_max,'2324','MACAO','A',''),
		(@v_max,'2325','MARTINICA','A',''),
		(@v_max,'2326','MAURITANIA','A',''),
		(@v_max,'2327','MONTSERRAT','A',''),
		(@v_max,'2328','MALTA','A',''),
		(@v_max,'2329','MAURICIO','A',''),
		(@v_max,'2330','MALDIVAS','A',''),
		(@v_max,'2331','MALAWI','A',''),
		(@v_max,'2332','MEXICO','A',''),
		(@v_max,'2333','MALASIA','A',''),
		(@v_max,'2334','MOZAMBIQUE','A',''),
		(@v_max,'2335','NAMIBIA','A',''),
		(@v_max,'2336','NUEVA CALEDONIA','A',''),
		(@v_max,'2337','NIGER','A',''),
		(@v_max,'2338','NIGERIA','A',''),
		(@v_max,'2339','NUEVAS HEBRIDAS','A',''),
		(@v_max,'2340','NICARAGUA','A',''),
		(@v_max,'2341','ISLA NORFOLF','A',''),
		(@v_max,'2342','HOLANDA','A',''),
		(@v_max,'2343','NORWAY-BOUVET ISLAND','A',''),
		(@v_max,'2344','NEPAL','A',''),
		(@v_max,'2345','NAURU','A',''),
		(@v_max,'2346','ISLA NIUE','A',''),
		(@v_max,'2347','NUEVA ZELANDIA','A',''),
		(@v_max,'2348','ORGANISMO INTERNACIONAL','A',''),
		(@v_max,'2349','OMAN','A',''),
		(@v_max,'2350','PANAMA','A',''),
		(@v_max,'2351','PALESTINA','A',''),
		(@v_max,'2352','ISLAS DEL PACIFICO','A',''),
		(@v_max,'2353','PERU','A',''),
		(@v_max,'2354','POLINESIA FRANCESA','A',''),
		(@v_max,'2355','PAPUA NUEVA GUINEA','A',''),
		(@v_max,'2356','FILIPINAS','A',''),
		(@v_max,'2357','PAKISTAN','A',''),
		(@v_max,'2358','POLONIA','A',''),
		(@v_max,'2359','S. PEDRO Y MIGELON','A',''),
		(@v_max,'2360','ISLAS PITCAIRN','A',''),
		(@v_max,'2361','PUERTO RICO','A',''),
		(@v_max,'2362','PORTUGAL','A',''),
		(@v_max,'2363','ISLAS DEL PACIFICO (EE.UU)','A',''),
		(@v_max,'2364','PARAGUAY','A',''),
		(@v_max,'2365','QATAR','A',''),
		(@v_max,'2366','REUNION','A',''),
		(@v_max,'2367','RHODESIA DEL SUR','A',''),
		(@v_max,'2368','RUMANIA','A',''),
		(@v_max,'2369','RUSIA','A',''),
		(@v_max,'2370','RWANDA','A',''),
		(@v_max,'2371','ARABIA SAUDITA','A',''),
		(@v_max,'2372','ISLAS SALOMON BRITANICAS','A',''),
		(@v_max,'2373','SEYCHELLES','A',''),
		(@v_max,'2374','SUDAN','A',''),
		(@v_max,'2375','SUECIA','A',''),
		(@v_max,'2376','SINGAPUR','A',''),
		(@v_max,'2377','ST.HELENA','A',''),
		(@v_max,'2378','SIRIA','A',''),
		(@v_max,'2379','ISLAS SVALBART Y JAN MAYEN','A',''),
		(@v_max,'2380','SIKKIM','A',''),
		(@v_max,'2381','SIERRA LEONA','A',''),
		(@v_max,'2382','SAN MARINO','A',''),
		(@v_max,'2383','SENEGAL','A',''),
		(@v_max,'2384','SOMALIA','A',''),
		(@v_max,'2385','SURINAME','A',''),
		(@v_max,'2386','SANTO TOME Y PRINCIPE','A',''),
		(@v_max,'2387','RUSIA-UKRAINIAN SSR','A',''),
		(@v_max,'2388','EL SALVADOR','A',''),
		(@v_max,'2389','SIRIA','A',''),
		(@v_max,'2390','SWAZILANDIA','A',''),
		(@v_max,'2391','ISLAS TURCAS Y CAICOS','A',''),
		(@v_max,'2392','CHAD','A',''),
		(@v_max,'2393','TOGO','A',''),
		(@v_max,'2394','TAILANDIA','A',''),
		(@v_max,'2395','ISLAS TOKELAU','A',''),
		(@v_max,'2396','TUNISIA','A',''),
		(@v_max,'2397','TUNEZ','A',''),
		(@v_max,'2398','TONGA','A',''),
		(@v_max,'2399','EAST TIMOR','A',''),
		(@v_max,'2400','TURQUIA','A',''),
		(@v_max,'2401','TRINIDAD Y TOBAGO','A',''),
		(@v_max,'2402','TAIWAN','A',''),
		(@v_max,'2403','REP. TANZANIA','A',''),
		(@v_max,'2404','RSS DE UCRANIA','A',''),
		(@v_max,'2405','UGANDA','A',''),
		(@v_max,'2406','ESTADOS UNIDOS-GUAM-HAITI-PANA','A',''),
		(@v_max,'2407','ESTADOS UNIDOS','A',''),
		(@v_max,'2408','URUGUAY','A',''),
		(@v_max,'2409','UZBEKISTAN','A',''),
		(@v_max,'2410','CIUDAD DEL VATICANO','A',''),
		(@v_max,'2411','SAN VICENTE','A',''),
		(@v_max,'2412','VENEZUELA','A',''),
		(@v_max,'2413','ISLAS VIRGENES BRITANICAS','A',''),
		(@v_max,'2414','VIETNAM','A',''),
		(@v_max,'2415','VANUATU','A',''),
		(@v_max,'2416','ISLAS WALLIS FUTUNA','A',''),
		(@v_max,'2417','ISLA WAKE','A',''),
		(@v_max,'2418','SAMOA ACCIDENTAL','A',''),
		(@v_max,'2419','CAMERUN-CONGO-GUINEA ECUATORIA','A',''),
		(@v_max,'2420','ANGUILA','A',''),
		(@v_max,'2421','BENIN-BURKINA FASO-NIGER','A',''),
		(@v_max,'2422','NUEVA CALEDONIA-FRENCH POLYNES','A',''),
		(@v_max,'2423','YEMEN DEMOCRATICO','A',''),
		(@v_max,'2424','YEMEN','A',''),
		(@v_max,'2425','YUGOSLAVIA','A',''),
		(@v_max,'2426','SUDAFRICA','A',''),
		(@v_max,'2427','ZAMBIA','A',''),
		(@v_max,'2428','ZAIRE','A',''),
		(@v_max,'2429','ZIMBABWE','A',''),
		(@v_max,'20006','INDIA','A',''),
		(@v_max,'20007','COREA DEL SUR','A',''),
		(@v_max,'20008','UCRANIA','A',''),
		(@v_max,'20009','CROACIA','A',''),
		(@v_max,'20355','CAMERUN-CONGO-GUINEA ECUATORIA','A',''),
		(@v_max,'20627','ZIMBABWE','A',''),
		(@v_max,'20628','TAYIKISTAN','A',''),
		(@v_max,'20629','PALESTINA','A',''),
		(@v_max,'39652','ESTONIA','A',''),
		(@v_max,'40074','TAYIKISTAN','A',''),
		(@v_max,'40728','ESLOVAQUIA','A',''),
		(@v_max,'46332','SERBIA','A',''),
		(@v_max,'46333','BIRMANIA','A',''),
		(@v_max,'46334','NORUEGA','A','')


end
	
go
