//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.WCFEnvioCorreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFEnvioCorreo.ServEnvioClientSoap")]
    public interface ServEnvioClientSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PI_UsrEnvia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse EnviarCorreo(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse> EnviarCorreoAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PI_UsrEnvia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreoAdjunto", ReplyAction="*")]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse EnviarCorreoAdjunto(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreoAdjunto", ReplyAction="*")]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse> EnviarCorreoAdjuntoAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PI_UsrEnvia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaCorreoApi", ReplyAction="*")]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse EnviaCorreoApi(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaCorreoApi", ReplyAction="*")]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse> EnviaCorreoApiAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreo", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequestBody Body;
        
        public EnviarCorreoRequest() {
        }
        
        public EnviarCorreoRequest(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PI_UsrEnvia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PI_UsrDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PI_UsrDestinoCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PI_UsrDestinoCCO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PI_Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PI_Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool PI_MostrarLogo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool PI_EsHTML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool PI_TieneAdjuntos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PI_Adjunto;
        
        public EnviarCorreoRequestBody() {
        }
        
        public EnviarCorreoRequestBody(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, string PI_Adjunto) {
            this.PI_UsrEnvia = PI_UsrEnvia;
            this.PI_UsrDestino = PI_UsrDestino;
            this.PI_UsrDestinoCC = PI_UsrDestinoCC;
            this.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            this.PI_Asunto = PI_Asunto;
            this.PI_Mensaje = PI_Mensaje;
            this.PI_MostrarLogo = PI_MostrarLogo;
            this.PI_EsHTML = PI_EsHTML;
            this.PI_TieneAdjuntos = PI_TieneAdjuntos;
            this.PI_Adjunto = PI_Adjunto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponseBody Body;
        
        public EnviarCorreoResponse() {
        }
        
        public EnviarCorreoResponse(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarCorreoResult;
        
        public EnviarCorreoResponseBody() {
        }
        
        public EnviarCorreoResponseBody(string EnviarCorreoResult) {
            this.EnviarCorreoResult = EnviarCorreoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoAdjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoAdjunto", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequestBody Body;
        
        public EnviarCorreoAdjuntoRequest() {
        }
        
        public EnviarCorreoAdjuntoRequest(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoAdjuntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PI_UsrEnvia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PI_UsrDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PI_UsrDestinoCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PI_UsrDestinoCCO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PI_Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PI_Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool PI_MostrarLogo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool PI_EsHTML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool PI_TieneAdjuntos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] PI_Adjunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string fileName;
        
        public EnviarCorreoAdjuntoRequestBody() {
        }
        
        public EnviarCorreoAdjuntoRequestBody(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName) {
            this.PI_UsrEnvia = PI_UsrEnvia;
            this.PI_UsrDestino = PI_UsrDestino;
            this.PI_UsrDestinoCC = PI_UsrDestinoCC;
            this.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            this.PI_Asunto = PI_Asunto;
            this.PI_Mensaje = PI_Mensaje;
            this.PI_MostrarLogo = PI_MostrarLogo;
            this.PI_EsHTML = PI_EsHTML;
            this.PI_TieneAdjuntos = PI_TieneAdjuntos;
            this.PI_Adjunto = PI_Adjunto;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoAdjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoAdjuntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponseBody Body;
        
        public EnviarCorreoAdjuntoResponse() {
        }
        
        public EnviarCorreoAdjuntoResponse(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoAdjuntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarCorreoAdjuntoResult;
        
        public EnviarCorreoAdjuntoResponseBody() {
        }
        
        public EnviarCorreoAdjuntoResponseBody(string EnviarCorreoAdjuntoResult) {
            this.EnviarCorreoAdjuntoResult = EnviarCorreoAdjuntoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCorreoApiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCorreoApi", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequestBody Body;
        
        public EnviaCorreoApiRequest() {
        }
        
        public EnviaCorreoApiRequest(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaCorreoApiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PI_UsrEnvia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PI_UsrDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PI_UsrDestinoCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PI_UsrDestinoCCO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PI_Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PI_Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool PI_MostrarLogo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool PI_EsHTML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool PI_TieneAdjuntos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] PI_Adjunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PI_NombrePlantilla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PI_Variables;
        
        public EnviaCorreoApiRequestBody() {
        }
        
        public EnviaCorreoApiRequestBody(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            this.PI_UsrEnvia = PI_UsrEnvia;
            this.PI_UsrDestino = PI_UsrDestino;
            this.PI_UsrDestinoCC = PI_UsrDestinoCC;
            this.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            this.PI_Asunto = PI_Asunto;
            this.PI_Mensaje = PI_Mensaje;
            this.PI_MostrarLogo = PI_MostrarLogo;
            this.PI_EsHTML = PI_EsHTML;
            this.PI_TieneAdjuntos = PI_TieneAdjuntos;
            this.PI_Adjunto = PI_Adjunto;
            this.fileName = fileName;
            this.PI_NombrePlantilla = PI_NombrePlantilla;
            this.PI_Variables = PI_Variables;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCorreoApiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCorreoApiResponse", Namespace="http://tempuri.org/", Order=0)]
        public AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponseBody Body;
        
        public EnviaCorreoApiResponse() {
        }
        
        public EnviaCorreoApiResponse(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaCorreoApiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaCorreoApiResult;
        
        public EnviaCorreoApiResponseBody() {
        }
        
        public EnviaCorreoApiResponseBody(string EnviaCorreoApiResult) {
            this.EnviaCorreoApiResult = EnviaCorreoApiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServEnvioClientSoapChannel : AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServEnvioClientSoapClient : System.ServiceModel.ClientBase<AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap>, AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap {
        
        public ServEnvioClientSoapClient() {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServEnvioClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServEnvioClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviarCorreo(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreo(request);
        }
        
        public string EnviarCorreo(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, string PI_Adjunto) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse retVal = ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviarCorreo(inValue);
            return retVal.Body.EnviarCorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse> AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviarCorreoAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoResponse> EnviarCorreoAsync(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, string PI_Adjunto) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            return ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviarCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviarCorreoAdjunto(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest request) {
            return base.Channel.EnviarCorreoAdjunto(request);
        }
        
        public string EnviarCorreoAdjunto(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse retVal = ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviarCorreoAdjunto(inValue);
            return retVal.Body.EnviarCorreoAdjuntoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse> AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviarCorreoAdjuntoAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest request) {
            return base.Channel.EnviarCorreoAdjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoResponse> EnviarCorreoAdjuntoAsync(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviarCorreoAdjuntoRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            return ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviarCorreoAdjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviaCorreoApi(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest request) {
            return base.Channel.EnviaCorreoApi(request);
        }
        
        public string EnviaCorreoApi(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            inValue.Body.PI_NombrePlantilla = PI_NombrePlantilla;
            inValue.Body.PI_Variables = PI_Variables;
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse retVal = ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviaCorreoApi(inValue);
            return retVal.Body.EnviaCorreoApiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse> AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap.EnviaCorreoApiAsync(AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest request) {
            return base.Channel.EnviaCorreoApiAsync(request);
        }
        
        public System.Threading.Tasks.Task<AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiResponse> EnviaCorreoApiAsync(string PI_UsrEnvia, string PI_UsrDestino, string PI_UsrDestinoCC, string PI_UsrDestinoCCO, string PI_Asunto, string PI_Mensaje, bool PI_MostrarLogo, bool PI_EsHTML, bool PI_TieneAdjuntos, byte[] PI_Adjunto, string fileName, string PI_NombrePlantilla, string PI_Variables) {
            AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest inValue = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequest();
            inValue.Body = new AngularJSAuthentication.API.WCFEnvioCorreo.EnviaCorreoApiRequestBody();
            inValue.Body.PI_UsrEnvia = PI_UsrEnvia;
            inValue.Body.PI_UsrDestino = PI_UsrDestino;
            inValue.Body.PI_UsrDestinoCC = PI_UsrDestinoCC;
            inValue.Body.PI_UsrDestinoCCO = PI_UsrDestinoCCO;
            inValue.Body.PI_Asunto = PI_Asunto;
            inValue.Body.PI_Mensaje = PI_Mensaje;
            inValue.Body.PI_MostrarLogo = PI_MostrarLogo;
            inValue.Body.PI_EsHTML = PI_EsHTML;
            inValue.Body.PI_TieneAdjuntos = PI_TieneAdjuntos;
            inValue.Body.PI_Adjunto = PI_Adjunto;
            inValue.Body.fileName = fileName;
            inValue.Body.PI_NombrePlantilla = PI_NombrePlantilla;
            inValue.Body.PI_Variables = PI_Variables;
            return ((AngularJSAuthentication.API.WCFEnvioCorreo.ServEnvioClientSoap)(this)).EnviaCorreoApiAsync(inValue);
        }
    }
}
