CREATE TABLE [Notificacion].[Notificacion] (
    [Codigo]           INT           IDENTITY (1, 1) NOT NULL,
    [Titulo]           VARCHAR (MAX) NULL,
    [Comunicado]       VARCHAR (MAX) NULL,
    [FechaVencimiento] DATETIME      NULL,
    [Categoria]        CHAR (1)      NULL,
    [Prioridad]        CHAR (1)      NULL,
    [Obligatorio]      CHAR (1)      NULL,
    [Tipo]             CHAR (1)      NULL,
    [FecEnvio]         DATETIME      NULL,
    [Ruta]             VARCHAR (100) NULL,
    [CodAgrupacion]    INT           NULL,
    [UsrIngreso]       VARCHAR (MAX) NULL,
    [FecIngreso]       DATETIME      NULL,
    [UsrModifica]      VARCHAR (50)  NULL,
    [FecModifica]      DATETIME      NULL,
    [UsrAprobacion]    VARCHAR (MAX) NULL,
    [FecAprobacion]    DATETIME      NULL,
    [Observacion]      VARCHAR (200) NULL,
    [Estado]           CHAR (1)      NULL,
    [MsjCorreo]        VARCHAR (MAX) NULL,
    [TipoCorreo]       VARCHAR (1)   NULL,
    [FechaPublicacion] DATETIME      NULL,
    [CorreoEnviado]    VARCHAR (1)   CONSTRAINT [DF_Notificacion_CorreoEnviado] DEFAULT ('N') NULL,
    [FechaEnvio]       DATETIME      NULL,
    [Corporativo]      BIT           NULL,
    CONSTRAINT [PK_Notificacion] PRIMARY KEY CLUSTERED ([Codigo] ASC)
);

